const organos = [
  "Encefalo",
  "Medula Espinal",
  "Nervio",
  "Ganglio Nervios",
  "Piel",
  "Una",
  "Pelo",
  "Corazon",
  "Venas",
  "Arteria",
  "Ganglio Linfatico",
  "Timo",
  "Bazo",
  "Lengua",
  "Esofago",
  "Estomago",
  "Intestino Delgado",
  "Intestino Grueso",
  "Diente",
  "Glandula Salivar",
  "Pancrea",
  "Higado",
  "Rinon",
  "Vejiga",
  "Tranquea",
  "Bronquios",
  "Tejido Respiratorio",
  "Tiroides",
  "Parotidas",
  "Suprarrenales",
  "Ovario",
  "Testiculo",
  "Hueso",
  "Musculo Esqueletico",
  "Otros"
];

module.exports = organos;
